### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by troyliu0105** [fbbdev/plot#20]
The last commit is 3 years ago... :sad:

**Comment by fbbdev** [comment]
Hi, I'm not actively working on it anymore. I am still maintaining it though, and I will answer if someone opens an issue.

The library works perfectly well for free drawing in the terminal; however it's still missing real plotting support, as you can see from open issues. Initially I didn't have ideas about how to design the API, then I didn't have time, plus you don't need plotting from C++ very often so development stalled.

I am happy to accept contributions if they are in line with my code style and contain clean template code.

**Comment by fbbdev** [comment]
You can also use it as a drawing base to implement your own plotting functionality!
